import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import "../globals.css";

import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SignIn | JobHunt",
  description: "Generated by create next app",
};

interface children {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: children) {
  const session = await getServerSession(authOptions);

  if (session !== null) return redirect("/");

  return (
    <html lang="en">
      <body className={epilogue.className} suppressHydrationWarning={true}>
        <main className="flex justify-center items-center min-h-screen">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
